import { Conversation, Message } from '../types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    name: '张伟',
    type: 'private',
    lastMessage: '好的，明天见！',
    unreadCount: 2,
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 minutes ago
  },
  {
    id: '2',
    name: '产品团队',
    type: 'group',
    lastMessage: '李娜: 新版本的设计稿已经上传了',
    unreadCount: 15,
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 minutes ago
  },
  {
    id: '3',
    name: '王芳',
    type: 'private',
    lastMessage: '收到，谢谢！',
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
  },
  {
    id: '4',
    name: '技术讨论组',
    type: 'group',
    lastMessage: '赵强: 这个问题我来看看',
    unreadCount: 5,
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
  },
  {
    id: '5',
    name: '刘洋',
    type: 'private',
    lastMessage: '周末一起打球吗？',
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
  },
  {
    id: '6',
    name: '陈静',
    type: 'private',
    lastMessage: '文档我已经发给你了',
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
  },
  {
    id: '7',
    name: '运营小组',
    type: 'group',
    lastMessage: '孙敏: 下周的活动方案需要大家确认',
    unreadCount: 120,
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
  },
  {
    id: '8',
    name: '周杰',
    type: 'private',
    lastMessage: '好的，我知道了',
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 1 week ago
  },
];

// Mock messages for testing
export const mockMessages: Message[] = [
  // Messages for conversation '1' (张伟)
  {
    id: 'm1',
    conversationId: '1',
    senderId: 'user1',
    senderName: '张伟',
    content: '你好！最近怎么样？',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm2',
    conversationId: '1',
    senderId: 'me',
    senderName: '我',
    content: '挺好的，你呢？',
    timestamp: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },
  {
    id: 'm3',
    conversationId: '1',
    senderId: 'user1',
    senderName: '张伟',
    content: '也不错，明天有空吗？一起吃个饭？',
    timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm4',
    conversationId: '1',
    senderId: 'me',
    senderName: '我',
    content: '好啊，几点？',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },
  {
    id: 'm5',
    conversationId: '1',
    senderId: 'user1',
    senderName: '张伟',
    content: '中午12点怎么样？',
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm6',
    conversationId: '1',
    senderId: 'me',
    senderName: '我',
    content: '好的，明天见！',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },

  // Messages for conversation '2' (产品团队)
  {
    id: 'm7',
    conversationId: '2',
    senderId: 'user2',
    senderName: '李娜',
    content: '大家好，新版本的设计稿已经上传了',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm8',
    conversationId: '2',
    senderId: 'user3',
    senderName: '王明',
    content: '收到，我看看',
    timestamp: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm9',
    conversationId: '2',
    senderId: 'me',
    senderName: '我',
    content: '设计稿看起来不错，有几个细节想讨论一下',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },
  {
    id: 'm10',
    conversationId: '2',
    senderId: 'user2',
    senderName: '李娜',
    content: '好的，你说',
    timestamp: new Date(Date.now() - 23 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm11',
    conversationId: '2',
    senderId: 'me',
    senderName: '我',
    content: '首页的布局是不是可以更紧凑一些？',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },
  {
    id: 'm12',
    conversationId: '2',
    senderId: 'user2',
    senderName: '李娜',
    content: '嗯，有道理，我调整一下',
    timestamp: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm13',
    conversationId: '2',
    senderId: 'user4',
    senderName: '赵强',
    content: '我觉得配色方案也可以优化',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm14',
    conversationId: '2',
    senderId: 'user2',
    senderName: '李娜',
    content: '好的，我会考虑的',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm15',
    conversationId: '2',
    senderId: 'me',
    senderName: '我',
    content: '那我们下午开个会详细讨论吧',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },

  // Messages for conversation '3' (王芳)
  {
    id: 'm16',
    conversationId: '3',
    senderId: 'user5',
    senderName: '王芳',
    content: '文档发给你了，记得查收',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm17',
    conversationId: '3',
    senderId: 'me',
    senderName: '我',
    content: '收到，谢谢！',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },

  // Messages for conversation '4' (技术讨论组)
  {
    id: 'm18',
    conversationId: '4',
    senderId: 'user6',
    senderName: '刘洋',
    content: '有人遇到过这个bug吗？',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm19',
    conversationId: '4',
    senderId: 'user4',
    senderName: '赵强',
    content: '这个问题我来看看',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm20',
    conversationId: '4',
    senderId: 'me',
    senderName: '我',
    content: '我之前也遇到过类似的问题',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },
  {
    id: 'm21',
    conversationId: '4',
    senderId: 'user6',
    senderName: '刘洋',
    content: '怎么解决的？',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm22',
    conversationId: '4',
    senderId: 'me',
    senderName: '我',
    content: '需要更新一下依赖版本',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },
  {
    id: 'm23',
    conversationId: '4',
    senderId: 'user4',
    senderName: '赵强',
    content: '我试试看',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm24',
    conversationId: '4',
    senderId: 'user4',
    senderName: '赵强',
    content: '好了，问题解决了，谢谢！',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },

  // Messages for conversation '5' (刘洋) - with different statuses
  {
    id: 'm25',
    conversationId: '5',
    senderId: 'user6',
    senderName: '刘洋',
    content: '周末一起打球吗？',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm26',
    conversationId: '5',
    senderId: 'me',
    senderName: '我',
    content: '好啊，什么时候？',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: true,
  },
  {
    id: 'm27',
    conversationId: '5',
    senderId: 'user6',
    senderName: '刘洋',
    content: '周六下午3点',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000 + 35 * 60 * 1000).toISOString(),
    status: 'sent',
    isMine: false,
  },
  {
    id: 'm28',
    conversationId: '5',
    senderId: 'me',
    senderName: '我',
    content: '没问题，到时候见',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000 + 40 * 60 * 1000).toISOString(),
    status: 'sending',
    isMine: true,
  },
  {
    id: 'm29',
    conversationId: '5',
    senderId: 'me',
    senderName: '我',
    content: '在哪里打？',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    status: 'failed',
    isMine: true,
  },
];

